/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppDevToolsRouteImport } from './routes/_app/dev-tools'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDevToolsIndexRouteImport } from './routes/_app/dev-tools/index'
import { Route as AppDevToolsDataRouteImport } from './routes/_app/dev-tools/data'
import { Route as AppDevToolsEncodeRouteImport } from './routes/_app/dev-tools/encode'
import { Route as AppDevToolsImageRouteImport } from './routes/_app/dev-tools/image'
import { Route as AppDevToolsJsonRouteImport } from './routes/_app/dev-tools/json'
import { Route as AppDevToolsReadmeRouteImport } from './routes/_app/dev-tools/readme'
import { Route as AppDevToolsRsaRouteImport } from './routes/_app/dev-tools/rsa'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes/index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppDevToolsRoute = AppDevToolsRouteImport.update({
  id: '/dev-tools',
  path: '/dev-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDevToolsIndexRoute = AppDevToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsDataRoute = AppDevToolsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsEncodeRoute = AppDevToolsEncodeRouteImport.update({
  id: '/encode',
  path: '/encode',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsImageRoute = AppDevToolsImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsJsonRoute = AppDevToolsJsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsReadmeRoute = AppDevToolsReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppDevToolsRsaRoute = AppDevToolsRsaRouteImport.update({
  id: '/rsa',
  path: '/rsa',
  getParentRoute: () => AppDevToolsRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/dev-tools': typeof AppDevToolsRouteWithChildren
  '/notes': typeof AppNotesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/dev-tools/data': typeof AppDevToolsDataRoute
  '/dev-tools/encode': typeof AppDevToolsEncodeRoute
  '/dev-tools/image': typeof AppDevToolsImageRoute
  '/dev-tools/json': typeof AppDevToolsJsonRoute
  '/dev-tools/readme': typeof AppDevToolsReadmeRoute
  '/dev-tools/rsa': typeof AppDevToolsRsaRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/dev-tools/': typeof AppDevToolsIndexRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/settings': typeof AppSettingsRoute
  '/dev-tools/data': typeof AppDevToolsDataRoute
  '/dev-tools/encode': typeof AppDevToolsEncodeRoute
  '/dev-tools/image': typeof AppDevToolsImageRoute
  '/dev-tools/json': typeof AppDevToolsJsonRoute
  '/dev-tools/readme': typeof AppDevToolsReadmeRoute
  '/dev-tools/rsa': typeof AppDevToolsRsaRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/dev-tools': typeof AppDevToolsIndexRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/dev-tools': typeof AppDevToolsRouteWithChildren
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/dev-tools/data': typeof AppDevToolsDataRoute
  '/_app/dev-tools/encode': typeof AppDevToolsEncodeRoute
  '/_app/dev-tools/image': typeof AppDevToolsImageRoute
  '/_app/dev-tools/json': typeof AppDevToolsJsonRoute
  '/_app/dev-tools/readme': typeof AppDevToolsReadmeRoute
  '/_app/dev-tools/rsa': typeof AppDevToolsRsaRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/dev-tools/': typeof AppDevToolsIndexRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/dev-tools'
    | '/notes'
    | '/settings'
    | '/dev-tools/data'
    | '/dev-tools/encode'
    | '/dev-tools/image'
    | '/dev-tools/json'
    | '/dev-tools/readme'
    | '/dev-tools/rsa'
    | '/notes/$noteId'
    | '/dev-tools/'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/settings'
    | '/dev-tools/data'
    | '/dev-tools/encode'
    | '/dev-tools/image'
    | '/dev-tools/json'
    | '/dev-tools/readme'
    | '/dev-tools/rsa'
    | '/notes/$noteId'
    | '/dev-tools'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/dev-tools'
    | '/_app/notes'
    | '/_app/settings'
    | '/_app/dev-tools/data'
    | '/_app/dev-tools/encode'
    | '/_app/dev-tools/image'
    | '/_app/dev-tools/json'
    | '/_app/dev-tools/readme'
    | '/_app/dev-tools/rsa'
    | '/_app/notes/$noteId'
    | '/_app/dev-tools/'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev-tools': {
      id: '/_app/dev-tools'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof AppDevToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev-tools/': {
      id: '/_app/dev-tools/'
      path: '/'
      fullPath: '/dev-tools/'
      preLoaderRoute: typeof AppDevToolsIndexRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/data': {
      id: '/_app/dev-tools/data'
      path: '/data'
      fullPath: '/dev-tools/data'
      preLoaderRoute: typeof AppDevToolsDataRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/encode': {
      id: '/_app/dev-tools/encode'
      path: '/encode'
      fullPath: '/dev-tools/encode'
      preLoaderRoute: typeof AppDevToolsEncodeRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/image': {
      id: '/_app/dev-tools/image'
      path: '/image'
      fullPath: '/dev-tools/image'
      preLoaderRoute: typeof AppDevToolsImageRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/json': {
      id: '/_app/dev-tools/json'
      path: '/json'
      fullPath: '/dev-tools/json'
      preLoaderRoute: typeof AppDevToolsJsonRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/readme': {
      id: '/_app/dev-tools/readme'
      path: '/readme'
      fullPath: '/dev-tools/readme'
      preLoaderRoute: typeof AppDevToolsReadmeRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/dev-tools/rsa': {
      id: '/_app/dev-tools/rsa'
      path: '/rsa'
      fullPath: '/dev-tools/rsa'
      preLoaderRoute: typeof AppDevToolsRsaRouteImport
      parentRoute: typeof AppDevToolsRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
  }
}

interface AppDevToolsRouteChildren {
  AppDevToolsDataRoute: typeof AppDevToolsDataRoute
  AppDevToolsEncodeRoute: typeof AppDevToolsEncodeRoute
  AppDevToolsImageRoute: typeof AppDevToolsImageRoute
  AppDevToolsJsonRoute: typeof AppDevToolsJsonRoute
  AppDevToolsReadmeRoute: typeof AppDevToolsReadmeRoute
  AppDevToolsRsaRoute: typeof AppDevToolsRsaRoute
  AppDevToolsIndexRoute: typeof AppDevToolsIndexRoute
}

const AppDevToolsRouteChildren: AppDevToolsRouteChildren = {
  AppDevToolsDataRoute: AppDevToolsDataRoute,
  AppDevToolsEncodeRoute: AppDevToolsEncodeRoute,
  AppDevToolsImageRoute: AppDevToolsImageRoute,
  AppDevToolsJsonRoute: AppDevToolsJsonRoute,
  AppDevToolsReadmeRoute: AppDevToolsReadmeRoute,
  AppDevToolsRsaRoute: AppDevToolsRsaRoute,
  AppDevToolsIndexRoute: AppDevToolsIndexRoute,
}

const AppDevToolsRouteWithChildren = AppDevToolsRoute._addFileChildren(
  AppDevToolsRouteChildren,
)

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppDevToolsRoute: typeof AppDevToolsRouteWithChildren
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppDevToolsRoute: AppDevToolsRouteWithChildren,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
